obj-y += ipi.o
obj-$(NAUT_CONFIG_LEGION_RT) += test_legion.o \
								hello_world.o \
								partitioning.o \
								#circuit.o \
								#circuit_cpu.o \
								#circuit_mapper.o 
								# custom_mapper.o \
								# multiple_partitions.o \
								# privileges.o \
								# physical_regions.o \
								# logical_regions.o \
								# global_vars.o \
								# index_tasks.o \
								# tasks_and_futures.o	\
