# Each list element is a separate test
# There is only one run directive per test
# However, each test can be executed with several configs (listed by the configs option)
#
# NOTE: for qemu commands, you *must* add the -device isa-debug-exit flag, otherwise the test will not terminate!
# NOTE: you must make sure commands used in either the run or prep script are properly installed (this includes for Travis).
#       Edit the .travis.yml file if you need extra packages during an automated build test
# NOTE: "Run all tests from the testing framework at boot" *must* be enabled in your config
#
- example_test:
    configs:
        - default # this corresponds to configs/testing/default.config
        - full-debug
    prep: echo "Hello World"
    run: qemu-system-x86_64 -cdrom nautilus.iso -m 1G -serial stdio -device isa-debug-exit -monitor /dev/null -nographic
    test_flags:
        - "-test sampletest \"foo bar baz\""
        - "-test sampletest \"three more args\""


- provenance_test:
    configs:
        - prov_test
    prep: echo "Proveance test" 
    run: qemu-system-x86_64 -cdrom nautilus.iso -m 1G -serial stdio -device isa-debug-exit -monitor /dev/null -nographic
    test_flags:
        - "-test provtest \"bt foo\""
        - "-test provtest \"info 413064\""
