CFLAGS += -fopenmp -DOMPVER2 -DOMPVER3 -DSCHEDBENCH -DIDA=1 

	# $(MAKE) IDA=1 prog
	# $(MAKE) IDA=3 prog
	# $(MAKE) IDA=9 prog
	# $(MAKE) IDA=27 prog
	# $(MAKE) IDA=81 prog
	# $(MAKE) IDA=243 prog
	# $(MAKE) IDA=729 prog
	# $(MAKE) IDA=2187 prog
	# $(MAKE) IDA=6561 prog
	# $(MAKE) IDA=19683 prog
	# $(MAKE) IDA=59049 prog

obj-y += main.o \
	 common.o \
         arraybench.o \
         taskbench.o \

#        schedbench.o \



#         syncbench.o \


