
obj-$(NAUT_CONFIG_BASE_LIBC_COMPAT) += libccompat/
obj-$(NAUT_CONFIG_BASE_LIBM_COMPAT) += libmcompat/
obj-$(NAUT_CONFIG_BASE_LINUX_COMPAT) += linux/ 
obj-$(NAUT_CONFIG_BASE_PTHREAD_COMPAT) += pthread/


