CFLAGS += -Iinclude/net/lwip

obj-$(NAUT_CONFIG_NET_LWIP_APP_ECHO) += echo/
obj-$(NAUT_CONFIG_NET_LWIP_APP_HTTPD) += httpd/
obj-$(NAUT_CONFIG_NET_LWIP_APP_LWIP_SHELL) += shell/
obj-$(NAUT_CONFIG_NET_LWIP_APP_SOCKET_ECHO) += socket_echo/
obj-$(NAUT_CONFIG_NET_LWIP_APP_SOCKET_EXAMPLES) += socket_examples/
obj-$(NAUT_CONFIG_NET_LWIP_APP_LWIP_IPVCD) +=  ipvcd/

