obj-y = def.o \
	dns.o \
	inet_chksum.o \
	init.o \
	ip.o \
	mem.o \
	memp.o \
	netif.o \
	pbuf.o \
	raw.o \
	stats.o \
	sys.o \
	tcp.o \
	tcp_in.o \
	tcp_out.o \
	timeouts.o \
	udp.o

obj-y += ipv4/
#obj-y += ipv6/
