CFLAGS += -Isrc/gc/bdwgc/libatomic_ops \
	-Isrc/gc/bdwgc/libatomic_ops/atomic_ops \
	-Isrc/gc/bdwgc/libatomic_ops/atomic_ops/sysdeps \
	-Isrc/gc/bdwgc/libatomic_ops/atomic_ops/sysdeps/gcc \
	-UHAVE_GETPAGESIZE \
	-UHAVE_INTTYPES_H \
	-UHAVE_MEMORY_H \
	-UHAVE_MMAP \
	-UHAVE_STDINT_H \
	-UHAVE_STDLIB_H \
	-UHAVE_STRINGS_H \
	-UHAVE_SYS_PARAM_H \
	-UHAVE_SYS_STAT_H \
	-UHAVE_SYS_TYPES_H \
	-UHAVE_UNISTD_H \
	-USTDC_HEADERS \
	-U_PTHREADS \
	-U_REENTRANT \
	-DNAUT
obj-y += atomic_ops.o 

