CFLAGS += -w
obj-y += glue.o
obj-y += omptest/


# Note that we link with a patched version of the 
# libopenmp.a library from LLVM, so there is very little
# implementation here except glue code
#
# Note also that libc, linux, and pthread compatibility
# features must be turned on
#
