CXXFLAGS += -I. -DSHARED_LOWLEVEL -DCOMPILE_TIME_MIN_LEVEL=LEVEL_DEBUG 
#-DDEBUG_LOW_LEVEL -DDEBUG_HIGH_LEVEL 
#-I$(srctree)/include/EASTL
obj-y += alt_mappers.o \
		 shim_mapper.o \
		 default_mapper.o \
		 mapping_utilities.o \
		 garbage_collection.o \
		 legion.o \
		 legion_ops.o \
		 legion_spy.o \
		 legion_tasks.o \
		 legion_trace.o \
		 region_tree.o \
		 runtime.o \
		 shared_lowlevel.o \

