obj-y = auth.o \
	ccp.o \
	chap-md5.o \
	chap_ms.o \
	chap-new.o \
	demand.o \
	eap.o \
	ecp.o \
	eui64.o \
	fsm.o \
	ipcp.o \
	ipv6cp.o \
	lcp.o \
	magic.o \
	mppe.o \
	multilink.o \
	ppp.o \
	pppapi.o \
	pppcrypt.o \
	pppoe.o \
	pppol2tp.o \
	pppos.o \
	upap.o \
	utils.o \
	vj.o

obj-y += polarssl/
	 
	 
