obj-y += \
	fmtout.o \
	printk.o \
	doprnt.o \
	idt.o \
	queue.o \
	irq.o \
	mb_utils.o \
	paging.o \
	naut_string.o \
	msr.o \
	cpuid.o \
	spinlock.o \
	rwlock.o \
	condvar.o \
	smp.o \
	idle.o \
	thread.o \
	barrier.o \
	libccompat.o \
	hello_world.o \
	nautilus.o \
	libccompat.o \
	cxxglue.o \
	asm/ \
	dev/ \
	test/  \
	legion_runtime/
	
	
