obj-y += \
	nautilus/ \
	arch/ \
	asm/ \
	dev/ \
        fs/  \
	acpi/ \
	test/  

obj-$(NAUT_CONFIG_CXX_SUPPORT) += cxx/
obj-$(NAUT_CONFIG_LEGION_RT) += legion_runtime/
obj-$(NAUT_CONFIG_NDPC_RT) +=
obj-$(NAUT_CONFIG_NESL_RT) += 
obj-$(NAUT_CONFIG_NESL_RT) += 
