obj-y += \
	fmtout.o \
	printk.o \
	doprnt.o \
	idt.o \
	queue.o \
	irq.o \
	mb_utils.o \
	paging.o \
	naut_string.o \
	msr.o \
	cpuid.o \
	fpu.o \
	spinlock.o \
	mcslock.o \
	ticketlock.o \
	rwlock.o \
	condvar.o \
	hashtable.o \
	rbtree.o \
	random.o \
	smp.o \
	idle.o \
	thread.o \
	barrier.o \
	backtrace.o \
	cpu.o \
	mwait.o \
	acpi.o \
	shutdown.o \
	numa.o \
	nautilus.o \
	libccompat.o 

obj-$(NAUT_CONFIG_PROFILE) += instrument.o
